[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[[deploy.env]]
name = "NODE_ENV"
value = "production"

[[deploy.env]]
name = "PORT"
value = "3000"
